apiVersion: v1
kind: Secret
metadata:
  name: vaa-observer-env
  namespace: wormhole
type: Opaque
stringData:
  .env: |
    RUST_LOG=info,wormhole_vaa_observer_backend::domain::wormhole::handler=debug
    HOST=127.0.0.1
    PORT=3000
    API_TITLE="wormhole-vaa-observer-backend"
    WORMHOLESCAN_BASE_URL="https://api.wormholescan.io/api/v1"
    WORMHOLE_SPY_ADDR="127.0.0.1:7073"