apiVersion: v1
kind: Service
metadata:
  name: vaa-observer-backend-service
  namespace: wormhole
spec:
  type: NodePort
  ports:
    - port: 8080 
      targetPort: 3000
      nodePort: 30180
  selector:
    app: vaa-observer-backend 